name: project-check
on: push
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: installation
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test-coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test-coverage
